version: '3'
services:
  ding-dong:
    build: dingdong
    ports:
      - "8090:8090"
  envoy:                          # actual container name
    image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.12.2.1-prod
    user: "1337"

    environment:
            - APPMESH_VIRTUAL_NODE_NAME=mesh/demo/virtualNode/dingdong-node
            - ENVOY_LOG_LEVEL=info
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=AKIAV2PDSSJC3F4V27N2
            - AWS_SECRET_ACCESS_KEY=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
    network_mode: host

  proxyinit:                     # injector container
    image: subfuzion/aws-appmesh-proxy-route-manager:latest
    cap_add:
      - ALL
    environment:
      - APPMESH_START_ENABLED=1
      - APPMESH_IGNORE_UID=1337
      - APPMESH_ENVOY_INGRESS_PORT=15000
      - APPMESH_ENVOY_EGRESS_PORT=15001
      - APPMESH_APP_PORTS=8090
      - APPMESH_EGRESS_IGNORED_IP=169.254.169.254

