version: '3'
services:
  ping-pong:
    build: pingpong
    environment:
      - DING_HOST=dingdong.demo
      - DING_PORT=8090
    ports:
      - "8080:8080"
  envoy:                          # actual container name
    image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.12.2.1-prod
    user: "1337"
    environment:
            - APPMESH_VIRTUAL_NODE_NAME=mesh/demo/virtualNode/pingpong-node
            - ENVOY_LOG_LEVEL=info
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=<aws-id>
            - AWS_SECRET_ACCESS_KEY=<aws-key>
    network_mode: host

  proxyinit:                     # injector container 
    image: subfuzion/aws-appmesh-proxy-route-manager:latest
    cap_add:
      - ALL
    environment:
      - APPMESH_START_ENABLED=1
      - APPMESH_IGNORE_UID=1337
      - APPMESH_ENVOY_INGRESS_PORT=15000
      - APPMESH_ENVOY_EGRESS_PORT=15001
      - APPMESH_APP_PORTS=8080
      - APPMESH_EGRESS_IGNORED_IP=169.254.169.254

